### ISSUE TITLE
Different URL on prod/dev

### ISSUE THREAD

**Issue by seysn** [ludovicOuvry/BasketBack#3]
We want different datasource in the file [application.properties](https://github.com/ludovicOuvry/BasketBack/blob/master/src/main/resources/application.properties#L2).

When we're working on the prod environment, we want a datasource such as `basket-mysql:3306/basketbdd` instead of `localhost:3306/basketbdd`.

**Comment by ludovicOuvry** [comment]
ça vous va si c'est un argument à mettre lors du build du jar ?

**Comment by ludovicOuvry** [comment]
maintenant vous pouvez compile comme ça :  java -jar target/gs-rest-service-0.1.0.jar --spring.config.location=src/main/resources/application-prod.properties

**Comment by deregnab** [comment]
OK

**Comment by deregnab** [comment]
How can we use the command in order to realize test during the compilation ?

**Comment by ludovicOuvry** [comment]
test is automatic run during compilation whit a maven package i think
