### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by seysn** [ludovicOuvry/BasketBack#5]
After resolving #3, we will need some backend tests.

**Comment by ludovicOuvry** [comment]
there are some execution test, you need to put the right url in application.properties

**Comment by deregnab** [comment]
We can't modify the code because we're running the compilation on jenkins so the pull, compilation and deployment are automated

**Comment by ludovicOuvry** [comment]
yes i know i check if the spring.conf.location parameter  is avaible in maven

**Comment by ludovicOuvry** [comment]
now, you just need to set an $url variable system and it is automaticly set in application.properties. if it's needed we can modify this by using spring active pfile
